cfg_name: "scannet_mvdnet"

# dataset related
dataset: 'scannet'
dataset_path: '/mnt/bd/zw-volume/data/scannet/'
num_workers: 16
train_list: './data/train.txt'
test_list: './data/test.txt'

# training related
batch_size: 24
epochs: 15
learning_rate: 0.0002
momentum: 0.9
beta: 0.999
weight_decay: 0
print_freq: 20

# model related
model_name: 'MVDNet_conf'
ndepth: 64
mindepth: 0.5
maxdepth: 10.0
conf_dgamma: 5.0
conf_ngamma: 5.0
check_offsets: [1,3,5,10]
solver_alpha1: 1.0
solver_alpha2: 1.0
solver_sigma1: 50.0
solver_sigma2: 5.0
refine_iter: 5 # iterations of solver
pretrained_mvdn: ''

# loss related
d_weight: 0.7 # depth loss weight of the first term
n_weight: 3.0 # normal loss weight
nc_weight: 0.2 # normal confidence loss weight
dc_weight: 0.2 # depth confidence loss weight

# logging related
log_mode: 'summary' # or 'full'
output_dir: './results/stage1/'
save_samples: True


